baseurl = "https://gabrielecalvo.github.io"
languageCode = "en-us"
theme = "hugo-theme-stack"
paginate = 5
title = "Gabe Calvo"
DefaultContentLanguage = "en"
disqusShortname = "gabrielecalvo"

[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

  [params.footer]
  since = 2_019

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  # emoji = ""
  subtitle = "Energy Engineer working as Data Scientist with a passion for coding, travelling and learning."

    [params.sidebar.avatar]
    local = true
    src = "img/gabe.jpg"

  [params.article]
  math = false

    [params.article.license]
    enabled = false
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "disqus"

    [params.comments.utterances]
    issueTerm = "pathname"
    theme = "preferred-color-scheme"

  [params.widgets]
  enabled = [ "search", "archives", "tag-cloud" ]

    [params.widgets.archives]
    limit = 5
    path = "archives"

    [params.widgets.tagCloud]
    limit = 10

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

  [params.colorScheme]
  toggle = true
  default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
pre = "home"

[[menu.main]]
identifier = "about"
name = "About"
url = "about"
weight = -90
pre = "user"

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "archives"
weight = -70
pre = "archives"

[[menu.main]]
identifier = "search"
name = "Search"
url = "search"
weight = -60
pre = "search"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.highlight]
noClasses = false
